### PR TITLE
feature: relative prefix instead of only absolute hostname

### PR DESCRIPTION
**Pull request by juliusvonkohout**
Add the possibility to add a relative prefix instead of an absolute hostname. This is useful if you cannot easily get the full Hostname as for example on Kubernetes with an Istio ingressgateway.

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/patch-1*:refs/remotes/origin/patch-1* +refs/tags/patch-1*:refs/tags/patch-1*
  The process '/usr/bin/git' failed with exit code 1
```

this looks as if your checks are somewhat damaged.

**Comment by makseq** [comment]
Could you please check and say how it works with user avatars, uploaded images using GUI ?

**Comment by juliusvonkohout** [comment]
> Could you please check and say how it works with user avatars, uploaded images using GUI ?

it only works partially so far. I can login, see static images etc. What does not work is accessing /projects. /projects just returns a blank page

**Comment by makseq** [comment]
yes, it might be, because it's a very tricky thing (HOSTNAME) and it affects a lot of deep things.

**Comment by juliusvonkohout** [comment]
> yes, it might be, because it's a very tricky thing (HOSTNAME) and it affects a lot of deep things.

some script is not using it properly on the projects page
grafik

**Comment by juliusvonkohout** [comment]
closing, since this shall be the task of the maintainers.

**Pull request closed without merging**
